# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: macos-latest

   steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2 # Sets up R
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2 # Installs R package dependencies
        with:
          cache-version: 2
          extra-packages: |
            any::tidyverse
            any::knitr

      - name: Run R code (Example)
        run: |
          Rscript -e "install.packages('TDAvec', repos='http://cran.us.r-project.org')"
          Rscript -e "library('TDAvec'); options(rgl.useNULL=TRUE); devtools::test()"
    